name: DORA Metrics

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  dora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # 👈 Important!

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests
      
      - name: Run DORA metrics script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: python docs/dora_metrics.py

      - name: Commit and push DORA metrics
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "jitendractx"
          git config user.email "jitendractx@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/jitendractx/project01.git
          git add dora_metrics.json
          git commit -m "Update DORA metrics" || echo "No changes to commit"
          git push
