name: DORA Metrics

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  dora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run DORA Metrics Script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python docs/dora_metrics.py

      - name: Commit and Push DORA Metrics
        run: |
          git config user.name "jitendractx"
          git config user.email "jitendractx@users.noreply.github.com"
          git add docs/dora_metrics.json
          git commit -m "Update DORA metrics" || echo "No changes to commit"
          git push
