name: DORA Metrics

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  dora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run DORA metrics script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python dora_metrics.py

      - name: Commit metrics file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dora_metrics.json
          git commit -m "Update DORA metrics" || echo "No changes"
          git push
